version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    tty: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=kbj
    ports:
      - 3306:3306
    volumes:
      - ./volume/mysql:/var/lib/mysql

  redis:
    image: redis:7.2.4
    container_name: redis
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker-volume/redis/data:/data
