apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbj-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kbj
  template:
    metadata:
      labels:
        app: kbj
    spec:
      containers:
        - name: kbj-container
          image: kbj-nestjs-backend:1.0
          ports:
            - containerPort: 3001
