apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kbj-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kbj-deployment # Name of your deployment
  minReplicas: 2 # Minimum number of replicas
  maxReplicas: 5 # Maximum number of replicas
  metrics:
    - type: Pods
      pods:
        metric:
          name: requests_per_second # Name of your custom metric
        target:
          type: AverageValue
          averageValue: 2 # Target value for the metric
